"""Scaffold a new consumer device YAML from LumaDeck packages."""

from __future__ import annotations

from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[2]


def available(kind: str) -> list[str]:
    """List available themes / layouts / widgets in the repo."""

    folder = REPO_ROOT / kind
    if not folder.is_dir():
        return []
    return sorted(
        p.stem
        for p in folder.glob("*.yaml")
        if not p.stem.startswith("_")
    )


def generate(
    *,
    name: str,
    screen: str,
    theme: str,
    widgets: list[str],
    board: str = "esp32s3",
    include_ha: bool = True,
    include_nav: bool = True,
    out_dir: Path | None = None,
) -> Path:
    """Write a new device YAML and return its path."""

    if screen not in available("layouts"):
        raise ValueError(
            f"unknown layout {screen!r}. Available: {available('layouts')}"
        )
    if theme not in available("themes"):
        raise ValueError(
            f"unknown theme {theme!r}. Available: {available('themes')}"
        )
    bad = [w for w in widgets if w not in available("widgets")]
    if bad:
        raise ValueError(
            f"unknown widget(s) {bad}. Available: {available('widgets')}"
        )

    board_pkg = f"board_{board}"
    if not (REPO_ROOT / "packages" / f"{board_pkg}.yaml").is_file():
        raise ValueError(
            f"unknown board {board!r}. Try one of: esp32, esp32s3, esp32c3"
        )

    out_dir = out_dir or (REPO_ROOT / "examples")
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / f"{name}.yaml"

    lines: list[str] = []
    lines.append(f"# Generated by lumadeck for device '{name}'")
    lines.append("")
    lines.append("substitutions:")
    lines.append(f'  device_name:     "{name}"')
    lines.append(f'  device_friendly: "{name.replace("_", " ").title()}"')
    lines.append("")
    lines.append("packages:")
    lines.append("  core:    !include ../packages/core.yaml")
    lines.append(f"  board:   !include ../packages/{board_pkg}.yaml")
    lines.append(f"  theme:   !include ../themes/{theme}.yaml")
    lines.append("  fonts:   !include ../packages/fonts.yaml")
    lines.append("  display: !include ../packages/display.yaml")
    if include_ha:
        lines.append("  ha:      !include ../packages/ha.yaml")
    if include_nav:
        lines.append("  nav:     !include ../packages/nav.yaml")
    lines.append(f"  layout:  !include ../layouts/{screen}.yaml")
    width = max(9, max((len(w) for w in widgets), default=0) + 2)
    for w in widgets:
        key = f"{w}:".ljust(width)
        lines.append(f"  {key}!include ../widgets/{w}.yaml")

    lines.append("")
    lines.append(
        dedent(
            """\
            # ---- hardware-specific bits go below ----
            # Add your `display:` and (if any) `touchscreen:` blocks here.
            # See docs/consumer-repo-guide.md for examples per panel.
            """
        )
    )

    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path
